// 이 파일은 자동 생성 파일입니다. 직접 수정하지 마세요!
export const iconNames = [
  '404',
  'account',
  'add-timetable',
  'add',
  'apple',
  'arrow-back',
  'arrow-horizontal',
  'arrow-vertical',
  'check',
  'checkbox-active',
  'checkbox-default',
  'clear',
  'close',
  'copy',
  'delete',
  'download',
  'edit',
  'fesetival',
  'hamburger',
  'header-search',
  'heart-filled',
  'heart-outline',
  'indicator-active',
  'indicator-default',
  'kakao',
  'load',
  'logo-big',
  'logo-footer',
  'logo-placeholer',
  'logo-symbol',
  'logo-thumbnail',
  'meatball',
  'music',
  'overlay-info',
  'overlay-slide',
  'pause',
  'place',
  'play',
  'radio-active',
  'radio-default',
  'remove',
  'search-thumbnail',
  'search',
  'select',
  'setting',
  'switch',
  'time',
  'timetable-stroke',
  'toast-info',
  'warning',
] as const;

export type IconName = (typeof iconNames)[number];
