# - 특정 CVE 또는 패키지+CVE 조합을 무시하려면 아래 'ignore' 배열에 항목을 추가하세요.
# - 무시 항목에는 reason(사유)와 until(만료일)을 남기는 것을 권장합니다.
# - 예시 항목은 주석으로 남겨두었으니 필요 시 주석을 제거하고 수정해서 사용하세요.

ignore:
  - vulnerability: CVE-2025-47907
    package:
      name: stdlib
      type: go-module
    reason: 'Known false-positive from prebuilt esbuild binary built with go1.23.8; we rebuilt locally and validated. Temporary suppression until upstream confirms rebuild.'

  - vulnerability: CVE-2025-47906
    package:
      name: stdlib
      type: go-module
    reason: 'See CVE-2025-47907 notes; suppressing noise from prebuilt binary detection.'

  - vulnerability: CVE-2025-4673
    package:
      name: stdlib
      type: go-module
    reason: 'Temporary suppression for prebuilt esbuild binary detection.'

  - vulnerability: CVE-2025-0913
    package:
      name: stdlib
      type: go-module
    reason: 'Temporary suppression for prebuilt esbuild binary detection.'

  - vulnerability: CVE-2025-4674
    package:
      name: stdlib
      type: go-module
    reason: 'Temporary suppression for prebuilt esbuild binary detection.'
